Meta/WPT.sh: Install Ahem.ttf once for all chunked runners
Some runners were err'ing with the following message:

  FileNotFoundError: [Errno 2] No such file or directory:
  '/home/runner/.fonts/Ahem.ttf'

This was caused by our parallel runners all trying to install _and_
uninstall the Ahem font. At the end of a run, a runner could remove the
font leaving other runners with the mess.

This makes sure we install the Ahem font once before starting the
parallel runners.